version: "3.9"

services:
  db:
    image: postgres:15
    container_name: deploynova_db
    environment:
      POSTGRES_DB: deploynova
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - deploynova_net

  backend:
    build: ./backend
    container_name: deploynova_backend
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: deploynova
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - deploynova_net

  frontend:
    build: ./frontend
    container_name: deploynova_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - deploynova_net

networks:
  deploynova_net:

volumes:
  db_data:
